SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[USP_UPDATECONSUMERDATA_AI]                                
(                                
@M_Consumerid int,                                
@MobileNo nvarchar(20),                                
@ConsumerName nvarchar(max)=null,                                
@address nvarchar(max)=null,                                
@city nvarchar(100)=null,                                
@state nvarchar(100)=null,                                
@pin_code nvarchar(20)=null,                                
@Email nvarchar(max)=null,                                
@Vrkabel_User_Type int=null,                                
@firm_name nvarchar(max)=null,                                
@Dob date=null,                                
@Gender nvarchar(50)=null,                                
@experience nvarchar(100)=null,                                
@ShopName nvarchar(max)=null,                                
@ShopAddress nvarchar(max)=null,                                
@District nvarchar(100)=null,                                
@adharcard_image nvarchar(max)=null,                                
@adharcard_back_image nvarchar(max)=null,                                
@pancard_image nvarchar(max)=null,                                
@passbook_image nvarchar(max)=null,                                
@Business_Card nvarchar(max)=null,                                
@Shop_Inside_Comp nvarchar(max)=null,                                
@Shop_Outside_Comp nvarchar(max)=null,                                
@p_city nvarchar(100)=null,                                
@p_state nvarchar(100)=null,                                
@p_address nvarchar(max)=null,                                
@p_pincode nvarchar(20)=null,                                
@bank_account_number nvarchar(100)=null,                                
@bank_name nvarchar(255)=null,                                
@bank_ifsc_code nvarchar(50)=null,                                
@bank_account_holder_name nvarchar(255)=null,                                
@pancard_number nvarchar(50)=null,                                
@pan_card_name nvarchar(255)=null,                                
@pan_dob date=null,                                
@adhaar_number nvarchar(50)=null,                                
@vpa_id nvarchar(100)=null,                                
@GST_Number nvarchar(50)=null,                                
@NomineeName nvarchar(100)=null,                                
@NomineeMobile nvarchar(20)=null,                                
@NomineeRelation nvarchar(100)=null,                                
@Profile_Date_Update datetime=null                                
)                                
as                                
begin                                
UPDATE [M_Consumer]                                
SET [ConsumerName] = COALESCE(@ConsumerName, ConsumerName),                                
[address] = COALESCE(@address, address),                                
[city] = COALESCE(@city, city),                                
[state] = COALESCE(@state, state),                                
[pin_code] = COALESCE(@pin_code, pin_code),                                
[Email] = COALESCE(@Email, Email),                                
[Vrkabel_User_Type] = COALESCE(@Vrkabel_User_Type, Vrkabel_User_Type),                                
[Firm_Name] = COALESCE(@firm_name, Firm_Name),                                
[DOB] = COALESCE(@Dob, DOB),                                
[Gender] = COALESCE(@Gender, Gender),                                
[Experience] = COALESCE(@experience, Experience),                                
[ShopName] = COALESCE(@ShopName, ShopName),                                
[ShopAddress] = COALESCE(@ShopAddress, ShopAddress),                                
[District] = COALESCE(@District, District),                                
[adharcard_image] = COALESCE(@adharcard_image, adharcard_image),                                
[adharcard_back_image] = COALESCE(@adharcard_back_image, adharcard_back_image),                                
[pancard_image] = COALESCE(@pancard_image, pancard_image),                                
[passbook_image] = COALESCE(@passbook_image, passbook_image),                                
[Business_Card] = COALESCE(@Business_Card, Business_Card),                                
[Shop_Inside_Comp] = COALESCE(@Shop_Inside_Comp, Shop_Inside_Comp),                                
[Shop_Outside_Comp] = COALESCE(@Shop_Outside_Comp, Shop_Outside_Comp),                                
[p_city] = COALESCE(@p_city, p_city),                                
[p_state] = COALESCE(@p_state, p_state),                                
[p_address] = COALESCE(@p_address, p_address),                                
[p_pincode] = COALESCE(@p_pincode, p_pincode),                                
[bank_account_number] = COALESCE(@bank_account_number, bank_account_number),                                
[bank_name] = COALESCE(@bank_name, bank_name),                                
[bank_ifsc_code] = COALESCE(@bank_ifsc_code, bank_ifsc_code),                                
[bank_account_holder_name] = COALESCE(@bank_account_holder_name, bank_account_holder_name),                                
[pancard_number] = COALESCE(@pancard_number, pancard_number),                                
[pan_card_name] = COALESCE(@pan_card_name, pan_card_name),                                
[pan_dob] = COALESCE(@pan_dob, pan_dob),                                
[adhaar_number] = COALESCE(@adhaar_number, adhaar_number),                                
[vpa_id] = COALESCE(@vpa_id, vpa_id),                                
[GST_Number] = COALESCE(@GST_Number, GST_Number),                                
[NomineeName] = COALESCE(@NomineeName, NomineeName),                                
[NomineeMobile] = COALESCE(@NomineeMobile, NomineeMobile),                                
[NomineeRelation] = COALESCE(@NomineeRelation, NomineeRelation),                                
[Profile_Date_Update] = COALESCE(@Profile_Date_Update, Profile_Date_Update),                                
[Is_Profile_Updated] = 1,                                
[Is_Update_Profile]=1                                
WHERE [M_Consumerid] = @M_Consumerid and MobileNo=@MobileNo                                
                                
SELECT 'Success' as Result                                
end
GO
