CREATE TABLE [dbo].[App_device_version](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Comp_ID] [nvarchar](100) NULL,
	[LatestVersion] [nvarchar](50) NOT NULL,
	[ApkDownloadUrl] [nvarchar](500) NOT NULL,
 CONSTRAINT [PK_App_device_version] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
