/****** Object:  Table [dbo].[BBigData_MConsumer]    Script Date: 3/2/2026 12:27:10 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BBigData_MConsumer](
	[BigDataM_Consumer_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[BigDataId] [int] NULL,
	[M_Consumerid] [int] NULL,
 CONSTRAINT [PK_BBigData_MConsumer] PRIMARY KEY CLUSTERED 
(
	[BigDataM_Consumer_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
