/****** Object:  Table [dbo].[Comp_Doc_Flag]    Script Date: 3/2/2026 12:27:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Comp_Doc_Flag](
	[Row_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[Comp_ID] [nvarchar](50) NOT NULL,
	[Doc_Id] [nvarchar](max) NULL,
	[Flag] [numeric](18, 0) NULL,
	[Remarks] [nvarchar](max) NULL,
 CONSTRAINT [PK__Comp_Doc_Flag__22751F6C] PRIMARY KEY CLUSTERED 
(
	[Row_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
