/****** Object:  Table [dbo].[Comp_Reg]    Script Date: 3/2/2026 12:27:10 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Comp_Reg](
	[Comp_ID] [nvarchar](50) NOT NULL,
	[Comp_Name] [nvarchar](50) NULL,
	[Comp_Cat_Id] [numeric](18, 0) NULL,
	[Comp_Email] [nvarchar](50) NULL,
	[WebSite] [nvarchar](50) NULL,
	[Address] [nvarchar](max) NULL,
	[City_ID] [numeric](18, 0) NULL,
	[Contact_Person] [nvarchar](50) NULL,
	[Mobile_No] [nvarchar](50) NULL,
	[Phone_No] [nvarchar](50) NULL,
	[Fax] [nvarchar](50) NULL,
	[Reg_Date] [datetime] NULL,
	[Password] [nvarchar](50) NULL,
	[Status] [numeric](18, 0) NULL,
	[Email_Vari_Flag] [numeric](18, 0) NULL,
	[Update_Flag] [numeric](18, 0) NULL,
	[Comp_Type] [nvarchar](50) NULL,
	[Upgrade_Date] [datetime] NULL,
	[Delete_Flag] [int] NULL,
	[IsRetailer] [int] NULL,
	[logo_path] [nvarchar](max) NULL,
	[ResiAddress] [nvarchar](255) NULL,
	[DirectorName] [nvarchar](55) NULL,
	[DirectorFatherName] [nvarchar](55) NULL,
	[AadharNumber] [varchar](12) NULL,
	[MinLimitAmount] [decimal](18, 2) NULL,
	[StateId] [int] NULL,
	[Gstin] [nvarchar](20) NULL,
	[FssiNo] [nvarchar](20) NULL,
	[MsmeNo] [nvarchar](20) NULL,
	[DirectorPan] [nvarchar](20) NULL,
	[CurrentStep] [int] NULL,
	[SalutationId] [int] NULL,
	[DirectorLastName] [varchar](100) NULL,
	[PANCardImage] [varchar](max) NULL,
	[Designation] [varchar](100) NULL,
	[DirectorPhoto] [varchar](max) NULL,
	[DirectorEmail] [varchar](100) NULL,
	[DirectorMobile] [varchar](20) NULL,
	[DirectorAddress] [varchar](max) NULL,
	[GSTRegistrationCertificate] [varchar](max) NULL,
	[CompanyPAN] [varchar](20) NULL,
	[CompanyPANDocument] [varchar](max) NULL,
	[SignAgreements] [varchar](max) NULL,
	[Pincode] [varchar](10) NULL,
	[Landline] [varchar](20) NULL,
	[CompanyIndustry] [varchar](200) NULL,
	[CompanyAddress] [varchar](max) NULL,
	[Draft_Id] [int] NULL,
	[LastLogin] [datetime] NULL,
	[gst_LegalBusinessName] [nvarchar](200) NULL,
	[gst_RegistrationStatus] [bit] NULL,
	[gst_BusinessConstitution] [nvarchar](200) NULL,
	[gst_TaxPayerType] [nvarchar](100) NULL,
	[gst_TradeName] [nvarchar](200) NULL,
	[gst_RegistrationDate] [nvarchar](50) NULL,
	[gst_BusinessAddress] [nvarchar](600) NULL,
	[comp_pan_type] [nvarchar](50) NULL,
	[comp_pan_status] [nvarchar](50) NULL,
	[fssai_license_active_flag] [bit] NULL,
 CONSTRAINT [PK_Comp_Reg] PRIMARY KEY CLUSTERED 
(
	[Comp_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
