/****** Object:  Table [dbo].[M_consumer_NewUsers]    Script Date: 3/2/2026 12:27:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[M_consumer_NewUsers](
	[M_Consumerid] [int] IDENTITY(1,1) NOT NULL,
	[User_ID] [nvarchar](50) NOT NULL,
	[ConsumerName] [nvarchar](150) NULL,
	[Email] [nvarchar](150) NULL,
	[MobileNo] [nvarchar](50) NULL,
	[City] [nvarchar](50) NULL,
	[PinCode] [nvarchar](10) NULL,
	[Password] [nvarchar](50) NULL,
	[Entry_Date] [datetime] NULL,
	[IsActive] [int] NULL,
	[IsDelete] [int] NULL,
	[Address] [nvarchar](500) NULL,
	[ReferralCode] [numeric](20, 0) NULL,
	[IsSharedReferralCode] [bit] NULL,
	[employeeID] [varchar](20) NULL,
	[distributorID] [varchar](20) NULL,
	[aadharNumber] [varchar](12) NULL,
	[aadharFile] [nvarchar](130) NULL,
	[aadharback] [nvarchar](130) NULL,
	[aadharUploadedate] [datetime] NULL,
	[aadharUploadedBy] [nvarchar](50) NULL,
	[Aadhar_source] [nvarchar](50) NULL,
	[village] [nvarchar](50) NULL,
	[district] [nvarchar](40) NULL,
	[state] [nvarchar](20) NULL,
	[country] [nvarchar](30) NULL,
	[Role_Id] [int] NULL,
	[Created_by] [varchar](16) NULL,
	[Comp_id] [nvarchar](20) NULL,
	[Per_Address] [nvarchar](max) NULL,
	[SellerName] [nvarchar](100) NULL,
	[Inox_User_Type] [varchar](5) NULL,
	[Vrkabel_User_Type] [int] NULL,
	[cin_number] [varchar](100) NULL,
	[ref_cin_number] [varchar](100) NULL,
	[designation] [nvarchar](20) NULL,
	[dob] [nvarchar](20) NULL,
	[gender] [varchar](15) NULL,
	[sur_name] [varchar](50) NULL,
	[communication_status] [int] NULL,
	[business_status] [int] NULL,
	[house_number] [varchar](20) NULL,
	[land_mark] [varchar](100) NULL,
	[owner_number] [varchar](50) NULL,
	[shop_name] [varchar](50) NULL,
	[pancard_number] [varchar](50) NULL,
	[gst_number] [varchar](50) NULL,
	[pan_card_file] [varchar](100) NULL,
	[shop_file] [varchar](100) NULL,
	[Other_Role] [varchar](50) NULL,
	[Additional] [varchar](70) NULL,
	[profile_image] [varchar](100) NULL,
	[VRKbl_KYC_status] [int] NULL,
	[remark] [varchar](250) NULL,
	[UPIId] [varchar](100) NULL,
	[panekycStatus] [varchar](20) NULL,
	[aadharkycStatus] [varchar](20) NULL,
	[bankekycStatus] [varchar](20) NULL,
	[PanHolderName] [varchar](70) NULL,
	[AadharHolderName] [varchar](70) NULL,
	[FirmName] [varchar](255) NULL,
	[Shop_address] [varchar](255) NULL,
	[Agegroup] [nvarchar](100) NULL,
	[Pancard_Status] [varchar](20) NULL,
	[Aadhar_Status] [varchar](20) NULL,
	[Passbook_Status] [varchar](20) NULL,
	[Ekyc_status] [varchar](20) NULL,
	[Location] [varchar](100) NULL,
	[AddressProof] [varchar](100) NULL,
	[UpiidImage] [varchar](255) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
