/****** Object:  Table [dbo].[M_CodeInfo]    Script Date: 3/2/2026 12:27:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[M_CodeInfo](
	[Row_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[TotalCodes] [numeric](18, 0) NULL,
	[LicenseCodes] [numeric](18, 0) NULL,
	[DemoCodes] [numeric](18, 0) NULL,
 CONSTRAINT [PK__M_CodeIn__7C36D05E442B18F2] PRIMARY KEY CLUSTERED 
(
	[Row_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
