/****** Object:  Table [dbo].[M_Consumer_Comp]    Script Date: 3/2/2026 12:27:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[M_Consumer_Comp](
	[Row_ID] [int] IDENTITY(1,1) NOT NULL,
	[M_Consumerid] [int] NOT NULL,
	[MobileNo] [nvarchar](15) NULL,
	[Comp_id] [nvarchar](50) NOT NULL,
	[City_ID] [nvarchar](50) NULL,
	[State_ID] [nvarchar](100) NULL,
	[Country_ID] [nvarchar](50) NULL,
	[PinCode] [nvarchar](10) NULL,
	[IsActive] [int] NULL,
	[IsDelete] [int] NULL,
	[Created_by] [varchar](100) NULL,
	[Created_Date] [datetime] NULL,
	[Updated_by] [varchar](100) NULL,
	[Updated_Date] [datetime] NULL,
	[Inox_User_Type] [varchar](100) NULL,
	[Vrkabel_User_Type] [int] NULL,
	[ConsumerName] [nvarchar](150) NULL,
	[Email] [nvarchar](150) NULL,
	[Password] [nvarchar](50) NULL,
	[Entry_Date] [datetime] NULL,
	[Address] [nvarchar](500) NULL,
	[Per_Address] [nvarchar](500) NULL,
	[ReferralCode] [numeric](18, 0) NULL,
	[IsSharedReferralCode] [bit] NULL,
	[employeeID] [varchar](20) NULL,
	[distributorID] [varchar](20) NULL,
	[aadharNumber] [varchar](12) NULL,
	[aadharFile] [varchar](1000) NULL,
	[aadharback] [varchar](1000) NULL,
	[aadharUploadedate] [datetime] NULL,
	[aadharUploadedBy] [nvarchar](50) NULL,
	[Aadhar_source] [nvarchar](50) NULL,
	[Role_Id] [int] NULL,
	[SellerName] [nvarchar](255) NULL,
	[token] [nvarchar](200) NULL,
	[MStarId] [bigint] NULL,
	[cin_number] [varchar](100) NULL,
	[ref_cin_number] [varchar](100) NULL,
	[designation] [varchar](150) NULL,
	[dob] [varchar](100) NULL,
	[gender] [varchar](50) NULL,
	[sur_name] [varchar](50) NULL,
	[communication_status] [int] NULL,
	[business_status] [int] NULL,
	[house_number] [varchar](20) NULL,
	[land_mark] [varchar](100) NULL,
	[owner_number] [varchar](50) NULL,
	[shop_name] [varchar](500) NULL,
	[pancard_number] [varchar](50) NULL,
	[gst_number] [varchar](50) NULL,
	[pan_card_file] [varchar](100) NULL,
	[shop_file] [varchar](500) NULL,
	[Other_Role] [varchar](50) NULL,
	[profile_image] [nvarchar](200) NULL,
	[VRKbl_KYC_status] [int] NULL,
	[Additional] [varchar](70) NULL,
	[remark] [varchar](255) NULL,
	[panekycStatus] [varchar](20) NULL,
	[aadharkycStatus] [varchar](20) NULL,
	[bankekycStatus] [varchar](20) NULL,
	[PanHolderName] [varchar](70) NULL,
	[AadharHolderName] [varchar](70) NULL,
	[UPIId] [varchar](50) NULL,
	[Shop_address] [varchar](250) NULL,
	[FirmName] [varchar](500) NULL,
	[Apptoken] [varchar](255) NULL,
	[AppVersion] [varchar](20) NULL,
	[Agegroup] [nvarchar](50) NULL,
	[Village] [varchar](100) NULL,
	[District] [varchar](100) NULL,
	[User_ID] [nvarchar](50) NULL,
 CONSTRAINT [PK_M_Consumer_Comp_Consumer_Comp] PRIMARY KEY CLUSTERED 
(
	[M_Consumerid] ASC,
	[Comp_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
