/****** Object:  Table [dbo].[M_RandomPrize]    Script Date: 3/2/2026 12:27:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[M_RandomPrize](
	[Trans_Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Row_Id] [bigint] NOT NULL,
	[SST_Id] [bigint] NOT NULL,
	[Prize] [nvarchar](250) NULL,
	[IsUsed] [int] NULL,
 CONSTRAINT [PK_M_RandomPrize] PRIMARY KEY CLUSTERED 
(
	[Trans_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
