/****** Object:  Table [dbo].[M_Reason]    Script Date: 3/2/2026 12:27:10 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[M_Reason](
	[Reason_ID] [bigint] NOT NULL,
	[Reason] [nvarchar](max) NULL,
	[Type] [nvarchar](50) NOT NULL,
	[Status] [int] NULL,
 CONSTRAINT [PK_M_Reason] PRIMARY KEY CLUSTERED 
(
	[Reason_ID] ASC,
	[Type] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
