/****** Object:  Table [dbo].[Mail_SendDetail]    Script Date: 3/2/2026 12:27:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Mail_SendDetail](
	[tbl_id] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[Mail_id] [nvarchar](50) NULL,
	[Mail_To] [nvarchar](200) NULL,
 CONSTRAINT [PK_Mail_SendDetail] PRIMARY KEY CLUSTERED 
(
	[tbl_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
