/****** Object:  Table [dbo].[MenuItem_PFL]    Script Date: 3/2/2026 12:27:12 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MenuItem_PFL](
	[MenuItemID] [int] IDENTITY(1,1) NOT NULL,
	[MenuItemName] [nvarchar](100) NULL,
	[IsEnabled] [bit] NULL,
	[Request_Date] [datetime] NULL,
	[RefMenu] [int] NULL,
 CONSTRAINT [PK_MenuItem_PFLL] PRIMARY KEY CLUSTERED 
(
	[MenuItemID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
