/****** Object:  Table [dbo].[Price_Master]    Script Date: 3/2/2026 12:27:10 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Price_Master](
	[Row_Id] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[Pro_ID] [nvarchar](50) NOT NULL,
	[Rate_Per_Label] [numeric](18, 2) NULL,
 CONSTRAINT [PK_Price_Master] PRIMARY KEY CLUSTERED 
(
	[Pro_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
