/****** Object:  Table [dbo].[Sheet_emp100924]    Script Date: 3/2/2026 12:27:12 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Sheet_emp100924](
	[Zone] [nvarchar](255) NULL,
	[State] [nvarchar](255) NULL,
	[Dealer AO] [nvarchar](255) NULL,
	[Dealer Code] [nvarchar](255) NULL,
	[Dealer Name] [nvarchar](255) NULL,
	[Dealer Type] [nvarchar](255) NULL,
	[Dealer Operational Status] [nvarchar](255) NULL,
	[Location] [nvarchar](255) NULL,
	[Emp Code] [nvarchar](255) NULL,
	[Name] [nvarchar](255) NULL,
	[Star ID] [float] NULL,
	[Designation] [nvarchar](255) NULL,
	[Contact No] [nvarchar](255) NULL,
	[Joining Date] [datetime] NULL,
	[Status] [nvarchar](255) NULL,
	[KYC Status] [nvarchar](255) NULL,
	[Vendor Code] [nvarchar](255) NULL,
	[Aadhar No] [nvarchar](255) NULL,
	[Emp UID No] [nvarchar](255) NULL,
	[Based At] [nvarchar](255) NULL,
	[Branch Category] [nvarchar](255) NULL,
	[Branch Type] [nvarchar](255) NULL,
	[Gender] [nvarchar](255) NULL,
	[Father Name] [nvarchar](255) NULL,
	[DOB] [datetime] NULL,
	[Residence Location] [nvarchar](255) NULL,
	[Bank Account No] [nvarchar](255) NULL,
	[Bank KYC Status] [nvarchar](255) NULL,
	[PAN No] [nvarchar](255) NULL,
	[IFSCCode] [nvarchar](255) NULL,
	[PAN KYC Status] [nvarchar](255) NULL,
	[ID No] [nvarchar](255) NULL,
	[ID Proof] [nvarchar](255) NULL,
	[Bank KYC Updated on] [datetime] NULL,
	[PanCard KYC Updated on] [datetime] NULL,
	[Bank KYC Processed by Agency On] [nvarchar](255) NULL,
	[Pancard KYC Processed by Agency On] [nvarchar](255) NULL,
	[SAP Vendor Code Confirmation Recd On] [nvarchar](255) NULL,
	[Agency Remarks Bank] [nvarchar](255) NULL,
	[Agency Remarks Pancard] [nvarchar](255) NULL,
	[Resigned Date] [nvarchar](255) NULL,
	[Age] [nvarchar](255) NULL,
	[Employee Count] [float] NULL,
	[Authentication Date] [nvarchar](255) NULL,
	[Authentication Status] [nvarchar](255) NULL,
	[Authentication Remarks] [nvarchar](255) NULL
) ON [PRIMARY]
GO
