/****** Object:  Table [dbo].[SubCityMaster]    Script Date: 3/2/2026 12:27:12 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SubCityMaster](
	[SubCityMasterId] [int] IDENTITY(1,1) NOT NULL,
	[SubCityMasterName] [nvarchar](max) NOT NULL,
	[City_Id] [int] NOT NULL,
	[Flag] [int] NULL,
 CONSTRAINT [PK_dbo.SubCityMaster] PRIMARY KEY CLUSTERED 
(
	[SubCityMasterId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
