/****** Object:  Table [dbo].[tbl_USP_Support_Comp1152_010124_301124]    Script Date: 3/2/2026 12:27:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbl_USP_Support_Comp1152_010124_301124](
	[updated_by] [varchar](30) NULL,
	[UPDATEDDATE] [datetime] NULL,
	[enquiry_date] [datetime] NULL,
	[product_name] [nvarchar](50) NULL,
	[code1] [varchar](5) NULL,
	[code2] [varchar](8) NULL,
	[completecode] [varchar](82) NOT NULL,
	[status] [varchar](9) NOT NULL,
	[Mobile_Number] [nvarchar](13) NULL,
	[remarks] [varchar](200) NOT NULL,
	[Comments] [varchar](8000) NULL,
	[amount_won] [numeric](18, 0) NULL,
	[transaction_status] [nvarchar](50) NULL,
	[mode_of_verification] [varchar](20) NULL,
	[technicianid] [varchar](20) NULL,
	[dealercode] [varchar](20) NULL,
	[dealer_state] [varchar](50) NULL,
	[designation] [varchar](50) NULL,
	[consumername] [nvarchar](50) NULL,
	[city] [nvarchar](50) NULL,
	[address] [nvarchar](500) NULL,
	[pincode] [varchar](10) NULL,
	[aadharnumber] [varchar](12) NULL,
	[bank_name] [varchar](70) NULL,
	[account_holder_name] [varchar](70) NULL,
	[account_no] [nvarchar](50) NULL,
	[ifsc_code] [nvarchar](50) NULL,
	[branch] [nvarchar](255) NULL,
	[city_of_branch] [nvarchar](255) NULL,
	[br_address] [nvarchar](4000) NULL,
	[account_type] [nvarchar](50) NULL,
	[pro_id] [nvarchar](50) NULL,
	[aadharfile] [nvarchar](130) NULL,
	[aadharback] [nvarchar](130) NULL,
	[passbook] [varchar](150) NOT NULL,
	[location] [varchar](55) NULL,
	[consumerid] [int] NULL,
	[comp_id] [nvarchar](50) NULL,
	[bank_id] [nvarchar](50) NULL,
	[aadharUploadedBy] [varchar](30) NULL,
	[aadharUploadedate] [datetime] NULL,
	[Aadhar_source] [nvarchar](50) NULL,
	[psbUploadedate] [datetime] NULL,
	[psbUploadedBy] [varchar](30) NULL,
	[Passbook_source] [nvarchar](50) NULL,
	[User_ID] [nvarchar](50) NULL,
	[DealerType] [varchar](60) NULL,
	[pancard_number] [varchar](50) NULL,
	[pan_card_file] [varchar](100) NULL,
	[UPIId] [varchar](50) NULL,
	[Pancard_Status] [varchar](20) NULL,
	[Aadhar_Status] [varchar](20) NULL,
	[Passbook_Status] [varchar](20) NULL,
	[Ekyc_status] [varchar](20) NULL,
	[PanHolderName] [varchar](70) NULL,
	[Proprietor1] [varchar](100) NULL,
	[Proprietor2] [varchar](100) NULL,
	[Proprietor3] [varchar](100) NULL
) ON [PRIMARY]
GO
