/****** Object:  Table [dbo].[Tbl_ClientSPMapping]    Script Date: 3/2/2026 12:27:12 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tbl_ClientSPMapping](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Comp_Id] [varchar](15) NOT NULL,
	[SP_Name] [varchar](200) NOT NULL,
	[IsActive] [bit] NULL,
	[APIName] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
