name: Deploy SQL to Production (Database)

on:
  push:
    branches: 
      - main  # Triggers automatically when code is pushed/merged to the main branch
  workflow_dispatch:  # Allows you to click "Run workflow" manually on GitHub

jobs:
  deploy-prod:
    runs-on: [self-hosted, prod-server]
    environment: Prod Server
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run PROD DB Deployment Script
        shell: powershell
        env:
          DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
        run: |
          powershell -ExecutionPolicy Bypass -File ./deploy_db.ps1 -TargetEnv "PROD"
